### ISSUE TITLE
Unable to load script

### ISSUE THREAD

**Issue by Grabli66** [BabylonJS/BabylonReactNative#114]
I tried to run Playground app on Android device. But i get that error.

E/unknown:ReactNative: ReactInstanceManager.createReactContext: mJSIModulePackage null
E/ReactNativeJNI: logMarker CREATE_REACT_CONTEXT_END
E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:234)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:29)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:258)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1293)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:776)

**Comment by ryantrem** [comment]
Hi @Grabli66 - that usually indicates a misconfiguration of your environment or some tooling issue (e.g. Metro server not running etc.). Did you follow all the steps in the [readme](https://github.com/BabylonJS/BabylonReactNative/blob/master/README.md#contributing)? Will you list out here the exact steps you are taking?

**Comment by Grabli66** [comment]
Hi!
I did everything in readme for linux:
1. Install NDK 21.3.6528147
2. Install cmake 3.18.4
3. git clone https://github.com/BabylonJS/BabylonReactNative
4. cd BabylonReactNative
5. git submodule update --init --recursive
6. cd Apps/Playground
7. npm install
8. npm run android

> Playground@0.0.1 android /home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 991 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.

> Task :babylonjs_react-native:externalNativeBuildDebug
Build multiple targets turbomodulejsijni_armeabi-v7a BabylonNative_armeabi-v7a
ninja: Entering directory `/home/grabli66/WorkspaceTest/BabylonReactNative/Modules/@babylonjs/react-native/android/.cxx/cmake/debug/armeabi-v7a'
[1/4] Building CXX object CMakeFiles/turbomodulejsijni.dir/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni/ReactCommon/CallInvokerHolder.cpp.o
[2/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libturbomodulejsijni.so
[3/4] Building CXX object CMakeFiles/BabylonNative.dir/src/main/cpp/BabylonNativeInterop.cpp.o
[4/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libBabylonNative.so
Build multiple targets turbomodulejsijni_arm64-v8a BabylonNative_arm64-v8a
ninja: Entering directory `/home/grabli66/WorkspaceTest/BabylonReactNative/Modules/@babylonjs/react-native/android/.cxx/cmake/debug/arm64-v8a'
[1/4] Building CXX object CMakeFiles/turbomodulejsijni.dir/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni/ReactCommon/CallInvokerHolder.cpp.o
[2/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libturbomodulejsijni.so
[3/4] Building CXX object CMakeFiles/BabylonNative.dir/src/main/cpp/BabylonNativeInterop.cpp.o
[4/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libBabylonNative.so
Build multiple targets BabylonNative_x86 turbomodulejsijni_x86
ninja: Entering directory `/home/grabli66/WorkspaceTest/BabylonReactNative/Modules/@babylonjs/react-native/android/.cxx/cmake/debug/x86'
[1/4] Building CXX object CMakeFiles/turbomodulejsijni.dir/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni/ReactCommon/CallInvokerHolder.cpp.o
[2/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/x86/libturbomodulejsijni.so
[3/4] Building CXX object CMakeFiles/BabylonNative.dir/src/main/cpp/BabylonNativeInterop.cpp.o
[4/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/x86/libBabylonNative.so

> Task :app:stripDebugDebugSymbols UP-TO-DATE
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.

> Task :app:installDebug
11:16:33 V/ddms: execute: running am get-config
11:16:33 V/ddms: execute 'am get-config' on 'XMRNU17828105602' : EOF hit. Read: -1
11:16:33 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'BAH-L09 - 7.0' for app:debug
11:16:33 D/app-debug.apk: Uploading app-debug.apk onto device 'XMRNU17828105602'
11:16:33 D/Device: Uploading file onto device 'XMRNU17828105602'
11:16:33 D/ddms: Reading file permision of /home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/android/app/build/outputs/apk/debug/app-debug.apk as: rw-rw-r--
11:16:37 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
11:16:42 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'XMRNU17828105602' : EOF hit. Read: -1
11:16:42 V/ddms: execute: returning
11:16:42 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
11:16:42 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'XMRNU17828105602' : EOF hit. Read: -1
11:16:42 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 33s
89 actionable tasks: 6 executed, 83 up-to-date
info Connecting to the development server...
info Starting the app on "XMRNU17828105602"...
Starting: Intent { cmp=com.playground/.MainActivity }

**Comment by CedricGuillemet** [comment]
Let me check that!

**Comment by CedricGuillemet** [comment]
hi @Grabli66 
I was able to build and run on Android. 1 issue I've found is metro is not by the build script.
In a terminal, run this commands:
`
cd BabylonReactNative
cd Apps/Playground
npm run start
`
you should see the metro server running.
Kill the app if it's running on your device or emulator and in another terminal:
`
cd BabylonReactNative
cd Apps/Playground
npm run android
`
Let me know if it works for you.

**Comment by Grabli66** [comment]
npm run start
It almost helped me. :)
But now i get error from metro server.

error: Error: Unable to resolve module `metro/src/lib/bundle-modules/HMRClient` from `node_modules/react-native/Libraries/Utilities/HMRClient.js`: metro/src/lib/bundle-modules/HMRClient could not be found within the project or in these directories:
  /home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/metro/src/lib/bundle-modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/grabli66/WorkspaceTest/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

Tried some solutions from stackoverflow, and nothing helps.
I hate npm, react native and javascript :(

**Comment by CedricGuillemet** [comment]
I tried to remove metro folder from node_modules, run `npm install` in directory `Apps/Playground` then `npm run start` and it worked for me.
why do you use yarn instead of npm?

**Comment by Grabli66** [comment]
I use only npm. I hate it but use it :)
Don't know why exception have recomendations only for yarn.

I tried to clean node_modules. Clean /tmp/metro-*
npm install
But no luck. :(

Will check other solutions later, if i find them. And maybe will use some black magic.

**Comment by ryantrem** [comment]
I have seen errors like that HMRClient one in the past when using sym linked modules. I'm not sure if this is the problem for you, but it would be easy to test out. Simplest thing would be to try the PackageTest app instead of the Playground app, and easiest way to do that is to run `npm install @babylonjs/react-native` in the PackageTest directory (e.g. use the published package instead of a locally built package), then just run the usual `npm` and `npx` commands to build and run that app (PackageTest). If that works, then there might be something going on with the sym links.

Also, have you tried building/running other React Native apps on your Linux box? Is this problem specific to Babylon React Native, or does it repro for any React Native app?

**Comment by bghgary** [comment]
Closing due to inactivity. Please reopen if you still have issues or use the forums.
