### ISSUE TITLE
Playground app won't build for Android

### ISSUE THREAD

**Issue by HedwigAR** [BabylonJS/BabylonReactNative#190]
I have no problems for iOS but I can't get the app to run on Android.
I've followed the steps in the README and using the following versions of tools:
```
node -v
v15.12.0
```
```
java --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```
in android folder:
```
./gradlew --version
------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          13.0.2 (AdoptOpenJDK 13.0.2+8)
OS:           Mac OS X 10.16 x86_64
```
```
cmake --version    
cmake version 3.20.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
```
ninja --version
1.10.2
```

When running `npm run android` I get this error:
```
> Playground@0.0.1 android
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 939 file(s) to forward-jetify. Using 12 workers...
info Starting JS server...
info Installing the app...
> Task :babylonjs_react-native:generateJsonModelDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
73 actionable tasks: 5 executed, 68 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':babylonjs_react-native:generateJsonModelDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':babylonjs_react-native:generateJsonModelDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (/RedactedPathToBabylon/BabylonJSRN/BabylonReactNative/Apps/Playground/node_modules/execa/index.js:174:9)
    at /RedactedPathToBabylon/BabylonJSRN/BabylonReactNative/Apps/Playground/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async runOnAllDevices (/RedactedPathToBabylon/BabylonJSRN/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/RedactedPathToBabylon/BabylonJSRN/BabylonReactNative/Apps/Playground/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
npm ERR! code 1
npm ERR! path /RedactedPathToBabylon/BabylonJSRN/BabylonReactNative/Apps/Playground
npm ERR! command failed
npm ERR! command sh -c react-native run-android

npm ERR! A complete log of this run can be found in:
```

I'm quite sure there's something wrong in my setup since a collegue could get the project to run, but as far as I can see my versions match up with the README

**Comment by Drigax** [comment]
I've noticed this issue as well in some environments, including sporadically in our CI pipeline @bghgary, @ryantrem. 

In my experience, it may be related to Android Studio for Windows failing to build if our intermediates exceed the old windows PATH length limit, but the lack of failure detail from Android Studio definitely doesn't help. 

@HedwigAR can you confirm what platform that you're developing with?

**Comment by ryantrem** [comment]
It looks like this is related to https://github.com/BabylonJS/BabylonNative/issues/654. And it seems like that issue started happening consistently today, which makes me wonder if it is the result of some Android Studio or Gralde update?

**Comment by HedwigAR** [comment]
@Drigax Thanks for looking into this, I'm working on a Mac.

**Comment by ryantrem** [comment]
From what I can tell this is a regression in cmake 3.20. @HedwigAR - are you using 3.20? If so, will you try downgrading to 3.19? You will have to manually delete the `Modules/@babylonjs/react-native/android/.cxx` directory as even a clean gradle build won't do that.

**Comment by HedwigAR** [comment]
@ryantrem Sure! I'm back at my work on Tuesday. I'll report back with the results then.

**Comment by HedwigAR** [comment]
That did it, it builds with cmake version 3.19.7.
