### ISSUE TITLE
Error trying to run Playground app

### ISSUE THREAD

**Issue by jayypluss** [BabylonJS/BabylonReactNative#293]
I can't seem to get the playground app working on my physical (Android) device. When I run `npm run android` the following error happens:

```
BabylonReactNative/Apps/Playground on  master via  v14.0.0 took 8s ⌚  11:29:23  ❯ npm run android

> Playground@0.0.1 android /home/jonathanfk/Dev/clones/BabylonReactNative/Apps/Playground
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 939 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...

> Task :babylonjs_react-native:compileDebugJavaWithJavac

> Task :babylonjs_react-native:generateJsonModelDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
69 actionable tasks: 9 executed, 60 up-to-date
Note: /home/jonathanfk/Dev/clones/BabylonReactNative/Modules/@babylonjs/react-native/android/src/main/java/com/babylonreactnative/EngineViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':babylonjs_react-native:generateJsonModelDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /home/jonathanfk/Dev/clones/BabylonReactNative/Modules/@babylonjs/react-native/android/src/main/java/com/babylonreactnative/EngineViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':babylonjs_react-native:generateJsonModelDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at makeError (/home/jonathanfk/Dev/clones/BabylonReactNative/Apps/Playground/node_modules/execa/index.js:174:9)
    at /home/jonathanfk/Dev/clones/BabylonReactNative/Apps/Playground/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/home/jonathanfk/Dev/clones/BabylonReactNative/Apps/Playground/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/home/jonathanfk/Dev/clones/BabylonReactNative/Apps/Playground/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Playground@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Playground@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonathanfk/.npm/_logs/2021-10-13T14_29_49_369Z-debug.log
```

I'm building from linux terminal.

**To Reproduce**
1. Clone repo and install dependencies following [these steps](https://github.com/BabylonJS/BabylonReactNative#preparing-a-new-repo)
2. Run `npm start`
3. In another terminal instance run `npm run android`

**Expected behavior**
App should run on physical device.

**Other**
 - Platform: Running from linux to physical Android device.

**Comment by ryantrem** [comment]
This is a dup of https://github.com/BabylonJS/BabylonReactNative/issues/190. The short answer though is downgrade CMake to 3.19.6, or possibly upgrade Android Studio to 4.2+. I haven't tried the newer Android Studio route, but supposedly it works. If you try it, let us know what you find!
