### ISSUE TITLE
React Native 0.69 support

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#428]
**Is your feature request related to a problem? Please describe.**
React Native 0.69 was recently released, but has a [JSI ABI breaking change](https://github.com/facebook/hermes/commit/2b6d408980d7f23f50602fd88169c8a9881592a6). This means the existing BRN packages don't work with RN 0.69.

**Describe the solution you'd like**
Add another RN flavor for 0.69 and publish the corresponding package.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by saidmoya12** [comment]
Please add support to RN 68 too

**Comment by ryantrem** [comment]
@CedricGuillemet are you planning to publish a package with the 0.68 fix (the maven issue )?

**Comment by CedricGuillemet** [comment]
I've published the 1.3.0-preview (being tested with 1 of our partners) : https://www.npmjs.com/package/@babylonjs/react-native-iosandroid-0-65/v/1.3.0-preview

it contains the gradle/maven fix.

**Comment by saidmoya12** [comment]
Maven works but useEngine return null always, some idea?

Thanks

**Comment by ryantrem** [comment]
@saidmoya12 will you start a thread on the [forum](https://forum.babylonjs.com) and include some or all of your code so we can see what you are trying to do?

**Comment by runtothedoor** [comment]
Any updates?

**Comment by theonetheycallneo** [comment]
I'm reposting this here (from 0.68 issue) for 0.69 as well:

Does anyone have a workaround for RN 0.68 with BabylonJs for iOS?

```
2022-08-02 11:55:30.626774-0400 Wallet[68917:2936056] [javascript] Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'initialize' of null
TypeError: Cannot read property 'initialize' of null
    at ensureInitialized$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:653325:71)
    at call (native)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24153:23)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24133:34)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24184:30)
    at call (native)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24153:23)
    at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24191:30)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24215:19)
    at tryCallTwo (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24214:33)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24219:157)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24184:30)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:24305:69)
    at ensureInitialized (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:653312:38)
    at tryCreateAsync$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.vatomcorp.viewer:654279:123)
    at call (native)
```

package.json:
```
"@babylonjs/core": "5.17.1",
"@babylonjs/loaders": "5.17.1",
"@babylonjs/react-native": "1.2.0",
"@babylonjs/react-native-iosandroid-0-65": "1.2.0",
...
"react-native": "0.69.0",
```

Or do we have to downgrade to RN 0.65?

**Comment by CedricGuillemet** [comment]
It should work with RN 0.67.
